apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexus-scheduler.fullname" . }}-api
  labels:
    {{- include "nexus-scheduler.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  selector:
    {{- include "nexus-scheduler.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
