apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nexus-scheduler.fullname" . }}-api
  labels:
    {{- include "nexus-scheduler.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "nexus-scheduler.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        {{- include "nexus-scheduler.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      serviceAccountName: {{ include "nexus-scheduler.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: api
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}-api:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - containerPort: {{ .Values.api.port }}
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: {{ .Values.api.port | quote }}
            - name: LOG_LEVEL
              value: "info"
            - name: OIDC_ISSUER_URL
              value: {{ .Values.oidc.issuerUrl | quote }}
            - name: OIDC_CLIENT_ID
              value: {{ .Values.oidc.clientId | quote }}
            - name: OIDC_REDIRECT_URI
              value: {{ .Values.oidc.redirectUri | quote }}
          envFrom:
            - secretRef:
                name: {{ .Values.secrets.appSecretName }}
            - secretRef:
                name: {{ .Values.secrets.oidcSecretName }}
          livenessProbe:
            httpGet: { path: /healthz, port: {{ .Values.api.port }} }
            initialDelaySeconds: 5
            periodSeconds: 15
          readinessProbe:
            httpGet: { path: /readyz, port: {{ .Values.api.port }} }
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
