apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexus-scheduler.fullname" . }}-frontend
  labels:
    {{- include "nexus-scheduler.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  selector:
    {{- include "nexus-scheduler.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  ports:
    - port: 80
      targetPort: {{ .Values.frontend.port }}
