#!/usr/bin/env bash
# Generates a local .env (and docker/librechat/.env) with randomly
# generated secrets for the Docker Compose dev/test stack
# (REQUIREMENTS.md §9.2 — "randomly generated keys for testing... no
# committed default passwords/keys"). Safe to re-run: each file is left
# alone if it already exists, independently of the other.
set -euo pipefail

cd "$(dirname "$0")/.."

random_hex() {
  openssl rand -hex "$1"
}

if [ -f .env ]; then
  echo ".env already exists — leaving it as-is. Delete it first if you want fresh secrets."
else
  cat > .env <<EOF
# Generated by scripts/generate-local-env.sh — local Compose use only.
# Never commit this file (it's in .gitignore) and never reuse these
# values outside local dev/testing.

POSTGRES_DB=nexus_scheduler
POSTGRES_USER=nexus
POSTGRES_PASSWORD=$(random_hex 24)

REDIS_PASSWORD=$(random_hex 24)

SESSION_SECRET=$(random_hex 32)
API_KEY_ENCRYPTION_KEY=$(random_hex 32)

KEYCLOAK_ADMIN=admin
KEYCLOAK_ADMIN_PASSWORD=$(random_hex 16)

# Built-in break-glass admin (REQUIREMENTS §4) — this env var is the
# ongoing source of truth for its password, re-synced on every API
# startup, not just a one-time seed.
BOOTSTRAP_ADMIN_EMAIL=admin@nexus-scheduler.local
BOOTSTRAP_ADMIN_PASSWORD=$(random_hex 16)

# Points at the librechat service this same Compose stack now runs
# (see docker/librechat/.env for its own config) rather than an
# externally-run instance.
LIBRECHAT_BASE_URL=http://librechat:3080

# Claude/Anthropic as LibreChat's provider for local testing (optional
# — leave blank and LibreChat just won't offer it as an endpoint). Get
# a key at https://console.anthropic.com/ — docker-compose.yml passes
# this straight into the librechat container's environment.
ANTHROPIC_API_KEY=
EOF
  echo "Wrote .env with freshly generated local secrets."
  echo "Built-in admin: BOOTSTRAP_ADMIN_EMAIL / BOOTSTRAP_ADMIN_PASSWORD in .env"
  echo "Set ANTHROPIC_API_KEY in .env to use Claude as LibreChat's provider for testing."
fi

mkdir -p docker/librechat

if [ -f docker/librechat/.env ]; then
  echo "docker/librechat/.env already exists — leaving it as-is."
else
  cat > docker/librechat/.env <<EOF
# Generated by scripts/generate-local-env.sh — LibreChat's own config
# file (bind-mounted into the librechat container), separate from Nexus
# Scheduler's root .env. Never commit this file.

DOMAIN_CLIENT=http://localhost:3080
DOMAIN_SERVER=http://localhost:3080

ALLOW_REGISTRATION=true
ALLOW_EMAIL_LOGIN=true

JWT_SECRET=$(random_hex 32)
JWT_REFRESH_SECRET=$(random_hex 32)
CREDS_KEY=$(random_hex 32)
CREDS_IV=$(random_hex 16)

# At least one provider is required before you can create an Agent in
# LibreChat — it has nothing to call otherwise. Claude/Anthropic is set
# via ANTHROPIC_API_KEY in this repo's own root .env instead (docker-
# compose.yml injects it into this container, overriding anything set
# here) so there's one place to put it rather than two. Other providers
# still go here directly, then: docker compose restart librechat
OPENAI_API_KEY=
AZURE_API_KEY=
EOF
  echo "Wrote docker/librechat/.env."
  echo "Set ANTHROPIC_API_KEY in .env (root) to use Claude, or add another provider's key here."
fi

# Self-signed CA + server cert for the local syslog-test receiver
# (docker/syslog-test) — lets the syslog audit-event mirror's TLS/
# private-CA path (REQUIREMENTS §7.1) be exercised locally, the same way
# a real on-prem SIEM with a private-CA-signed cert would need it. Kept
# out of git (docker/generated/ is gitignored) since these are private
# keys, even though they're test-only and never leave localhost.
CERT_DIR="docker/generated/syslog-test-certs"
if [ -f "$CERT_DIR/ca.pem" ]; then
  echo "$CERT_DIR already has certs — leaving them as-is."
else
  mkdir -p "$CERT_DIR"
  openssl genrsa -out "$CERT_DIR/ca-key.pem" 2048 >/dev/null 2>&1
  openssl req -x509 -new -nodes -key "$CERT_DIR/ca-key.pem" -sha256 -days 3650 \
    -out "$CERT_DIR/ca.pem" -subj "/CN=Nexus Scheduler Local Test CA" >/dev/null 2>&1
  openssl genrsa -out "$CERT_DIR/server-key.pem" 2048 >/dev/null 2>&1
  openssl req -new -key "$CERT_DIR/server-key.pem" -out "$CERT_DIR/server.csr" \
    -subj "/CN=syslog-test" >/dev/null 2>&1
  cat > "$CERT_DIR/san.ext" <<EOF
subjectAltName=DNS:syslog-test,DNS:localhost,IP:127.0.0.1
EOF
  openssl x509 -req -in "$CERT_DIR/server.csr" -CA "$CERT_DIR/ca.pem" -CAkey "$CERT_DIR/ca-key.pem" \
    -CAcreateserial -out "$CERT_DIR/server-cert.pem" -days 3650 -sha256 \
    -extfile "$CERT_DIR/san.ext" >/dev/null 2>&1
  rm -f "$CERT_DIR/server.csr" "$CERT_DIR/san.ext" "$CERT_DIR/ca.srl"
  echo "Generated a local test CA + server cert for syslog-test at $CERT_DIR/."
  echo "Paste $CERT_DIR/ca.pem's contents into Admin Settings' syslog CA-certificate upload to test TLS locally."
fi
