#!/usr/bin/env bash
# Generates a local .env (and docker/librechat/.env) with randomly
# generated secrets for the Docker Compose dev/test stack
# (REQUIREMENTS.md §9.2 — "randomly generated keys for testing... no
# committed default passwords/keys"). Safe to re-run: each file is left
# alone if it already exists, independently of the other.
set -euo pipefail

cd "$(dirname "$0")/.."

random_hex() {
  openssl rand -hex "$1"
}

if [ -f .env ]; then
  echo ".env already exists — leaving it as-is. Delete it first if you want fresh secrets."
  # ...except for settings added after that .env was written, which the
  # Compose stack can't start without. Appending a missing key never
  # touches existing values, so re-running this stays safe.
  if ! grep -q '^LITELLM_MASTER_KEY=' .env; then
    cat >> .env <<EOF

# LiteLLM model gateway (LibreChat -> LiteLLM -> Ollama) — appended by
# scripts/generate-local-env.sh after this .env was first written. The
# master key is the gateway's admin credential (login for
# http://localhost:4000/ui); LibreChat authenticates with the dedicated
# virtual key, provisioned by the litellm-init service; the salt key
# encrypts provider credentials stored in LiteLLM's own Postgres.
LITELLM_MASTER_KEY=sk-$(random_hex 24)
LITELLM_SALT_KEY=sk-$(random_hex 24)
LITELLM_POSTGRES_PASSWORD=$(random_hex 24)
LITELLM_LIBRECHAT_KEY=sk-$(random_hex 24)
EOF
    echo "Appended freshly generated LiteLLM settings to the existing .env."
  elif ! grep -q '^LITELLM_LIBRECHAT_KEY=' .env; then
    cat >> .env <<EOF

# Dedicated LiteLLM virtual key for LibreChat (appended by
# scripts/generate-local-env.sh) — provisioned in the gateway by the
# litellm-init service; the master key stays admin-only.
LITELLM_LIBRECHAT_KEY=sk-$(random_hex 24)
EOF
    echo "Appended LITELLM_LIBRECHAT_KEY to the existing .env."
  fi
  if ! grep -q '^LITELLM_OCR_KEY=' .env; then
    cat >> .env <<EOF

# OCR vision-description settings (issue #145; OFF by default) — appended
# by scripts/generate-local-env.sh. LITELLM_OCR_KEY is provisioned in the
# gateway by litellm-init. To enable: OCR_DESCRIBE_IMAGES=true +
# OCR_VISION_MODEL=<a multimodal model, e.g. moondream:1.8b> added to
# OLLAMA_PULL_MODELS and uncommented in docker/litellm/config.yaml.
LITELLM_OCR_KEY=sk-$(random_hex 24)
OCR_DESCRIBE_IMAGES=false
OCR_VISION_MODEL=
OLLAMA_PULL_MODELS=gemma3:1b codegemma:2b phi4-mini-reasoning:3.8b
EOF
    echo "Appended OCR vision-description settings to the existing .env."
  fi
else
  cat > .env <<EOF
# Generated by scripts/generate-local-env.sh — local Compose use only.
# Never commit this file (it's in .gitignore) and never reuse these
# values outside local dev/testing.

POSTGRES_DB=nexus_scheduler
POSTGRES_USER=nexus
POSTGRES_PASSWORD=$(random_hex 24)

REDIS_PASSWORD=$(random_hex 24)

SESSION_SECRET=$(random_hex 32)
API_KEY_ENCRYPTION_KEY=$(random_hex 32)
PDF_SERVICE_SHARED_SECRET=$(random_hex 32)

KEYCLOAK_ADMIN=admin
KEYCLOAK_ADMIN_PASSWORD=$(random_hex 16)

# Built-in break-glass admin (REQUIREMENTS §4) — this env var is the
# ongoing source of truth for its password, re-synced on every API
# startup, not just a one-time seed.
BOOTSTRAP_ADMIN_EMAIL=admin@nexus-scheduler.local
BOOTSTRAP_ADMIN_PASSWORD=$(random_hex 16)

# Points at the librechat service this same Compose stack now runs
# (see docker/librechat/.env for its own config) rather than an
# externally-run instance.
LIBRECHAT_BASE_URL=http://librechat:3080

# LiteLLM model gateway (LibreChat -> LiteLLM -> Ollama) — meters every
# model call with per-key spend/budgets/rate limits. The master key is
# the gateway's admin credential (login for http://localhost:4000/ui);
# LibreChat itself authenticates with the dedicated virtual key below,
# provisioned by the litellm-init service — budgets and rate limits
# attach to virtual keys, and the admin credential stays out of the
# librechat container. The salt key encrypts provider credentials
# stored in LiteLLM's own Postgres (litellm-postgres service).
LITELLM_MASTER_KEY=sk-$(random_hex 24)
LITELLM_SALT_KEY=sk-$(random_hex 24)
LITELLM_POSTGRES_PASSWORD=$(random_hex 24)
LITELLM_LIBRECHAT_KEY=sk-$(random_hex 24)
# Dedicated gateway key for the OCR service's optional vision
# descriptions — provisioned as an llm_api-only key by litellm-init,
# exactly like the LibreChat key. Generated now so enabling the feature
# below is a one-line flip, not a manual key-provisioning chore (#145).
LITELLM_OCR_KEY=sk-$(random_hex 24)

# Optional vision descriptions of image inputs (issue #145). OFF by
# default. To turn on: set OCR_DESCRIBE_IMAGES=true and OCR_VISION_MODEL
# to a MULTIMODAL model, add that model to OLLAMA_PULL_MODELS and
# uncomment its entry in docker/litellm/config.yaml. A TEXT-ONLY model
# here yields silently missing descriptions (the OCR service now logs
# the gateway 400, but the feature still won't work). Example vision
# model: moondream:1.8b (small) or llava:7b (larger).
OCR_DESCRIBE_IMAGES=false
OCR_VISION_MODEL=
# Models the ollama-pull init container fetches on first start
# (space-separated). The default set is TEXT-ONLY; append a vision model
# here when enabling OCR_DESCRIBE_IMAGES above.
OLLAMA_PULL_MODELS=gemma3:1b codegemma:2b phi4-mini-reasoning:3.8b

# Claude/Anthropic for local testing (optional — leave blank and the
# gateway's claude-sonnet model just fails with an auth error if
# selected). Get a key at https://console.anthropic.com/ —
# docker-compose.yml passes this into the litellm container only, so
# hosted calls go through the gateway's metering/budgets like the
# local models (never handed to LibreChat directly).
ANTHROPIC_API_KEY=
EOF
  echo "Wrote .env with freshly generated local secrets."
  echo "Built-in admin: BOOTSTRAP_ADMIN_EMAIL / BOOTSTRAP_ADMIN_PASSWORD in .env"
  echo "Set ANTHROPIC_API_KEY in .env to use Claude as LibreChat's provider for testing."
fi

mkdir -p docker/librechat

if [ -f docker/librechat/.env ]; then
  echo "docker/librechat/.env already exists — leaving it as-is."
else
  cat > docker/librechat/.env <<EOF
# Generated by scripts/generate-local-env.sh — LibreChat's own config
# file (bind-mounted into the librechat container), separate from Nexus
# Scheduler's root .env. Never commit this file.

DOMAIN_CLIENT=http://localhost:3080
DOMAIN_SERVER=http://localhost:3080

ALLOW_REGISTRATION=true
ALLOW_EMAIL_LOGIN=true

JWT_SECRET=$(random_hex 32)
JWT_REFRESH_SECRET=$(random_hex 32)
CREDS_KEY=$(random_hex 32)
CREDS_IV=$(random_hex 16)

# At least one provider is required before you can create an Agent in
# LibreChat — it has nothing to call otherwise. Claude/Anthropic is set
# via ANTHROPIC_API_KEY in this repo's own root .env instead (docker-
# compose.yml injects it into this container, overriding anything set
# here) so there's one place to put it rather than two. Other providers
# still go here directly, then: docker compose restart librechat
OPENAI_API_KEY=
AZURE_API_KEY=
EOF
  echo "Wrote docker/librechat/.env."
  echo "Set ANTHROPIC_API_KEY in .env (root) to use Claude, or add another provider's key here."
fi

# Self-signed CA + server cert for the local syslog-test receiver
# (docker/syslog-test) — lets the syslog audit-event mirror's TLS/
# private-CA path (REQUIREMENTS §7.1) be exercised locally, the same way
# a real on-prem SIEM with a private-CA-signed cert would need it. Kept
# out of git (docker/generated/ is gitignored) since these are private
# keys, even though they're test-only and never leave localhost.
CERT_DIR="docker/generated/syslog-test-certs"
if [ -f "$CERT_DIR/ca.pem" ]; then
  echo "$CERT_DIR already has certs — leaving them as-is."
else
  mkdir -p "$CERT_DIR"
  openssl genrsa -out "$CERT_DIR/ca-key.pem" 2048 >/dev/null 2>&1
  openssl req -x509 -new -nodes -key "$CERT_DIR/ca-key.pem" -sha256 -days 3650 \
    -out "$CERT_DIR/ca.pem" -subj "/CN=Nexus Scheduler Local Test CA" >/dev/null 2>&1
  openssl genrsa -out "$CERT_DIR/server-key.pem" 2048 >/dev/null 2>&1
  openssl req -new -key "$CERT_DIR/server-key.pem" -out "$CERT_DIR/server.csr" \
    -subj "/CN=syslog-test" >/dev/null 2>&1
  cat > "$CERT_DIR/san.ext" <<EOF
subjectAltName=DNS:syslog-test,DNS:localhost,IP:127.0.0.1
EOF
  openssl x509 -req -in "$CERT_DIR/server.csr" -CA "$CERT_DIR/ca.pem" -CAkey "$CERT_DIR/ca-key.pem" \
    -CAcreateserial -out "$CERT_DIR/server-cert.pem" -days 3650 -sha256 \
    -extfile "$CERT_DIR/san.ext" >/dev/null 2>&1
  rm -f "$CERT_DIR/server.csr" "$CERT_DIR/san.ext" "$CERT_DIR/ca.srl"
  echo "Generated a local test CA + server cert for syslog-test at $CERT_DIR/."
  echo "Paste $CERT_DIR/ca.pem's contents into Admin Settings' syslog CA-certificate upload to test TLS locally."
fi
