#!/usr/bin/env bash
# Generates a local .env (and docker/librechat/.env) with randomly
# generated secrets for the Docker Compose dev/test stack
# (REQUIREMENTS.md §9.2 — "randomly generated keys for testing... no
# committed default passwords/keys"). Safe to re-run: each file is left
# alone if it already exists, independently of the other.
set -euo pipefail

cd "$(dirname "$0")/.."

random_hex() {
  openssl rand -hex "$1"
}

if [ -f .env ]; then
  echo ".env already exists — leaving it as-is. Delete it first if you want fresh secrets."
else
  cat > .env <<EOF
# Generated by scripts/generate-local-env.sh — local Compose use only.
# Never commit this file (it's in .gitignore) and never reuse these
# values outside local dev/testing.

POSTGRES_DB=nexus_scheduler
POSTGRES_USER=nexus
POSTGRES_PASSWORD=$(random_hex 24)

REDIS_PASSWORD=$(random_hex 24)

SESSION_SECRET=$(random_hex 32)
API_KEY_ENCRYPTION_KEY=$(random_hex 32)

KEYCLOAK_ADMIN=admin
KEYCLOAK_ADMIN_PASSWORD=$(random_hex 16)

# Built-in break-glass admin (REQUIREMENTS §4) — this env var is the
# ongoing source of truth for its password, re-synced on every API
# startup, not just a one-time seed.
BOOTSTRAP_ADMIN_EMAIL=admin@nexus-scheduler.local
BOOTSTRAP_ADMIN_PASSWORD=$(random_hex 16)

# Points at the librechat service this same Compose stack now runs
# (see docker/librechat/.env for its own config) rather than an
# externally-run instance.
LIBRECHAT_BASE_URL=http://librechat:3080
EOF
  echo "Wrote .env with freshly generated local secrets."
  echo "Built-in admin: BOOTSTRAP_ADMIN_EMAIL / BOOTSTRAP_ADMIN_PASSWORD in .env"
fi

mkdir -p docker/librechat

if [ -f docker/librechat/.env ]; then
  echo "docker/librechat/.env already exists — leaving it as-is."
else
  cat > docker/librechat/.env <<EOF
# Generated by scripts/generate-local-env.sh — LibreChat's own config
# file (bind-mounted into the librechat container), separate from Nexus
# Scheduler's root .env. Never commit this file.

DOMAIN_CLIENT=http://localhost:3080
DOMAIN_SERVER=http://localhost:3080

ALLOW_REGISTRATION=true
ALLOW_EMAIL_LOGIN=true

JWT_SECRET=$(random_hex 32)
JWT_REFRESH_SECRET=$(random_hex 32)
CREDS_KEY=$(random_hex 32)
CREDS_IV=$(random_hex 16)

# At least one of these is required before you can create an Agent in
# LibreChat — it has nothing to call otherwise. Fill in a real key,
# then: docker compose restart librechat
OPENAI_API_KEY=
ANTHROPIC_API_KEY=
AZURE_API_KEY=
EOF
  echo "Wrote docker/librechat/.env — add a provider API key before creating an Agent (see README)."
fi
